DROP DATABASE IF EXISTS SECRET_MESSAGES;
CREATE DATABASE SECRET_MESSAGES; 
USE SECRET_MESSAGES; 

CREATE TABLE USERS (
	ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR (255) NOT NULL,
    EMAIL VARCHAR (255) NOT NULL,
    LOGIN VARCHAR (255) NOT NULL,
    USER_PASSWORD VARCHAR (255) NOT NULL,
    PRIVATE_KEY VARBINARY (3000) NOT NULL,
    PUBLIC_KEY_PATH VARCHAR (255) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE MESSAGE (
	ID INT NOT NULL AUTO_INCREMENT,
    RECEIVER_ID INT NOT NULL,
	SENDER_ID INT NOT NULL, 
    CONTENT VARBINARY (5000) NOT NULL,
	PRIMARY KEY (ID)
);
